import "./globals.css";
import Header from "@/components/Header";
import { Container } from "@mui/material";
import styles from "./page.module.css";
import Footer from "@/components/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <body>
        <Container className={styles.container} maxWidth="md">
          <Header></Header>
          {children}
          <Footer></Footer>
        </Container>
      </body>
    </html>
  );
}
